import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * GeneratedDiagram — renders a diagram image generated by the Narrator Agent
 * as an HTML overlay anchored to a 3D world position via @react-three/drei Html.
 *
 * Receives the image URL and 3D position from response_chunk.content.generatedImage
 * or artifact_recall.content.generatedDiagrams.
 *
 * Usage inside a Canvas scene:
 *   <GeneratedDiagram url="..." position={{x:2.5, y:1.8, z:-2}} onDismiss={() => ...} />
 *
 * Usage as a plain HTML overlay (outside Canvas):
 *   <GeneratedDiagramCard url="..." caption="..." onDismiss={() => ...} />
 */
import { useState } from 'react';
import { Html } from '@react-three/drei';
export function GeneratedDiagram({ url, position, caption, onDismiss }) {
    const [loaded, setLoaded] = useState(false);
    return (_jsx(Html, { position: [position.x, position.y, position.z], center: true, distanceFactor: 4, style: { pointerEvents: 'auto' }, zIndexRange: [100, 110], children: _jsxs("div", { id: `generated-diagram-${encodeURIComponent(url).slice(-12)}`, style: containerStyle(loaded), children: [_jsx("button", { onClick: onDismiss, style: closeButtonStyle, "aria-label": "Dismiss diagram", title: "Dismiss", children: "\u00D7" }), _jsx("img", { src: url, alt: caption ?? 'Generated diagram', onLoad: () => setLoaded(true), style: imageStyle(loaded), draggable: false }), caption && _jsx("p", { style: captionStyle, children: caption }), !loaded && _jsx("div", { style: skeletonStyle, "aria-label": "Loading diagram\u2026" })] }) }));
}
export function GeneratedDiagramCard({ url, caption, onDismiss }) {
    const [loaded, setLoaded] = useState(false);
    return (_jsxs("div", { style: cardContainerStyle(loaded), children: [onDismiss && (_jsx("button", { onClick: onDismiss, style: closeButtonStyle, "aria-label": "Dismiss", title: "Dismiss", children: "\u00D7" })), _jsx("img", { src: url, alt: caption ?? 'Generated diagram', onLoad: () => setLoaded(true), style: imageStyle(loaded), draggable: false }), caption && _jsx("p", { style: captionStyle, children: caption }), !loaded && _jsx("div", { style: skeletonStyle })] }));
}
// ── Styles ────────────────────────────────────────────────────────────────────
const containerStyle = (loaded) => ({
    position: 'relative',
    background: 'rgba(10,10,18,0.92)',
    backdropFilter: 'blur(16px)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 12,
    overflow: 'hidden',
    maxWidth: 280,
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
    opacity: loaded ? 1 : 0.6,
    transition: 'opacity 0.3s ease',
});
const cardContainerStyle = (loaded) => ({
    ...containerStyle(loaded),
    maxWidth: '100%',
});
const imageStyle = (loaded) => ({
    display: 'block',
    width: '100%',
    height: 'auto',
    objectFit: 'contain',
    opacity: loaded ? 1 : 0,
    transition: 'opacity 0.4s ease',
});
const skeletonStyle = {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(90deg, rgba(255,255,255,0.04) 25%, rgba(255,255,255,0.08) 50%, rgba(255,255,255,0.04) 75%)',
    backgroundSize: '200% 100%',
    animation: 'skeleton-shimmer 1.5s ease-in-out infinite',
};
const captionStyle = {
    margin: '6px 12px 10px',
    color: 'rgba(255,255,255,0.55)',
    fontSize: 11,
    fontFamily: 'Inter, system-ui, sans-serif',
    lineHeight: 1.4,
    textAlign: 'center',
};
const closeButtonStyle = {
    position: 'absolute',
    top: 6,
    right: 8,
    background: 'rgba(0,0,0,0.4)',
    border: 'none',
    borderRadius: '50%',
    width: 22,
    height: 22,
    color: 'rgba(255,255,255,0.7)',
    cursor: 'pointer',
    fontSize: 16,
    lineHeight: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
};
