/**
 * GeneratedDiagram — renders a diagram image generated by the Narrator Agent
 * as an HTML overlay anchored to a 3D world position via @react-three/drei Html.
 *
 * Receives the image URL and 3D position from response_chunk.content.generatedImage
 * or artifact_recall.content.generatedDiagrams.
 *
 * Usage inside a Canvas scene:
 *   <GeneratedDiagram url="..." position={{x:2.5, y:1.8, z:-2}} onDismiss={() => ...} />
 *
 * Usage as a plain HTML overlay (outside Canvas):
 *   <GeneratedDiagramCard url="..." caption="..." onDismiss={() => ...} />
 */

import React, { useState } from 'react';
import { Html } from '@react-three/drei';

// ── 3D version (inside <Canvas>) ─────────────────────────────────────────────

interface GeneratedDiagramProps {
    url: string;
    position: { x: number; y: number; z: number };
    caption?: string;
    onDismiss: () => void;
}

export function GeneratedDiagram({ url, position, caption, onDismiss }: GeneratedDiagramProps) {
    const [loaded, setLoaded] = useState(false);

    return (
        <Html
            position={[position.x, position.y, position.z]}
            center
            distanceFactor={4}
            style={{ pointerEvents: 'auto' }}
            zIndexRange={[100, 110]}
        >
            <div
                id={`generated-diagram-${encodeURIComponent(url).slice(-12)}`}
                style={containerStyle(loaded)}
            >
                <button
                    onClick={onDismiss}
                    style={closeButtonStyle}
                    aria-label="Dismiss diagram"
                    title="Dismiss"
                >
                    ×
                </button>
                <img
                    src={url}
                    alt={caption ?? 'Generated diagram'}
                    onLoad={() => setLoaded(true)}
                    style={imageStyle(loaded)}
                    draggable={false}
                />
                {caption && <p style={captionStyle}>{caption}</p>}
                {!loaded && <div style={skeletonStyle} aria-label="Loading diagram…" />}
            </div>
        </Html>
    );
}

// ── Flat HTML version (outside canvas, for artifact detail modal etc.) ────────

interface GeneratedDiagramCardProps {
    url: string;
    caption?: string;
    onDismiss?: () => void;
}

export function GeneratedDiagramCard({ url, caption, onDismiss }: GeneratedDiagramCardProps) {
    const [loaded, setLoaded] = useState(false);

    return (
        <div style={cardContainerStyle(loaded)}>
            {onDismiss && (
                <button onClick={onDismiss} style={closeButtonStyle} aria-label="Dismiss" title="Dismiss">
                    ×
                </button>
            )}
            <img
                src={url}
                alt={caption ?? 'Generated diagram'}
                onLoad={() => setLoaded(true)}
                style={imageStyle(loaded)}
                draggable={false}
            />
            {caption && <p style={captionStyle}>{caption}</p>}
            {!loaded && <div style={skeletonStyle} />}
        </div>
    );
}

// ── Styles ────────────────────────────────────────────────────────────────────

const containerStyle = (loaded: boolean): React.CSSProperties => ({
    position: 'relative',
    background: 'rgba(10,10,18,0.92)',
    backdropFilter: 'blur(16px)',
    border: '1px solid rgba(255,255,255,0.1)',
    borderRadius: 12,
    overflow: 'hidden',
    maxWidth: 280,
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
    opacity: loaded ? 1 : 0.6,
    transition: 'opacity 0.3s ease',
});

const cardContainerStyle = (loaded: boolean): React.CSSProperties => ({
    ...containerStyle(loaded),
    maxWidth: '100%',
});

const imageStyle = (loaded: boolean): React.CSSProperties => ({
    display: 'block',
    width: '100%',
    height: 'auto',
    objectFit: 'contain',
    opacity: loaded ? 1 : 0,
    transition: 'opacity 0.4s ease',
});

const skeletonStyle: React.CSSProperties = {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(90deg, rgba(255,255,255,0.04) 25%, rgba(255,255,255,0.08) 50%, rgba(255,255,255,0.04) 75%)',
    backgroundSize: '200% 100%',
    animation: 'skeleton-shimmer 1.5s ease-in-out infinite',
};

const captionStyle: React.CSSProperties = {
    margin: '6px 12px 10px',
    color: 'rgba(255,255,255,0.55)',
    fontSize: 11,
    fontFamily: 'Inter, system-ui, sans-serif',
    lineHeight: 1.4,
    textAlign: 'center',
};

const closeButtonStyle: React.CSSProperties = {
    position: 'absolute',
    top: 6,
    right: 8,
    background: 'rgba(0,0,0,0.4)',
    border: 'none',
    borderRadius: '50%',
    width: 22,
    height: 22,
    color: 'rgba(255,255,255,0.7)',
    cursor: 'pointer',
    fontSize: 16,
    lineHeight: 1,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
};
