/**
 * GeneratedDiagram — renders a diagram image generated by the Narrator Agent
 * as an HTML overlay anchored to a 3D world position via @react-three/drei Html.
 *
 * Receives the image URL and 3D position from response_chunk.content.generatedImage
 * or artifact_recall.content.generatedDiagrams.
 *
 * Usage inside a Canvas scene:
 *   <GeneratedDiagram url="..." position={{x:2.5, y:1.8, z:-2}} onDismiss={() => ...} />
 *
 * Usage as a plain HTML overlay (outside Canvas):
 *   <GeneratedDiagramCard url="..." caption="..." onDismiss={() => ...} />
 */

import { useState } from 'react';
import { Html } from '@react-three/drei';

// ── 3D version (inside <Canvas>) ─────────────────────────────────────────────

interface GeneratedDiagramProps {
    url: string;
    position: { x: number; y: number; z: number };
    caption?: string;
    onDismiss: () => void;
}

export function GeneratedDiagram({ url, position, caption, onDismiss }: GeneratedDiagramProps) {
    const [loaded, setLoaded] = useState(false);

    return (
        <Html
            position={[position.x, position.y, position.z]}
            center
            distanceFactor={4}
            className="pointer-events-auto"
            zIndexRange={[100, 110]}
        >
            <div
                id={`generated-diagram-${encodeURIComponent(url).slice(-12)}`}
                className={`relative bg-glass backdrop-blur-md border border-border rounded-md overflow-hidden max-w-[280px] shadow-md transition-opacity duration-300 ${loaded ? 'opacity-100' : 'opacity-60'}`}
            >
                <button
                    onClick={onDismiss}
                    className="absolute top-1.5 right-2 bg-surface-hover border border-border-light rounded-full w-[22px] h-[22px] text-text-muted cursor-pointer text-base leading-none flex items-center justify-center z-10"
                    aria-label="Dismiss diagram"
                    title="Dismiss"
                >
                    ×
                </button>
                <img
                    src={url}
                    alt={caption ?? 'Generated diagram'}
                    onLoad={() => setLoaded(true)}
                    className={`block w-full h-auto object-contain transition-opacity duration-400 ${loaded ? 'opacity-100' : 'opacity-0'}`}
                    draggable={false}
                />
                {caption && <p className="my-1.5 mx-3 mb-2.5 text-text-secondary text-[11px] font-body leading-[1.4] text-center">{caption}</p>}
                {!loaded && <div className="absolute inset-0 bg-surface-alt animate-pulse" aria-label="Loading diagram…" />}
            </div>
        </Html>
    );
}

// ── Flat HTML version (outside canvas, for artifact detail modal etc.) ────────

interface GeneratedDiagramCardProps {
    url: string;
    caption?: string;
    onDismiss?: () => void;
}

export function GeneratedDiagramCard({ url, caption, onDismiss }: GeneratedDiagramCardProps) {
    const [loaded, setLoaded] = useState(false);
    const [isExpanded, setIsExpanded] = useState(false);

    return (
        <>
            <div
                className={`relative bg-glass backdrop-blur-md border border-border rounded-md overflow-hidden shadow-md transition-opacity duration-300 w-full cursor-pointer ${loaded ? 'opacity-100' : 'opacity-60'}`}
                onClick={() => setIsExpanded(true)}
            >
                {onDismiss && (
                    <button
                        onClick={(e) => {
                            e.stopPropagation();
                            onDismiss();
                        }}
                        className="absolute top-1.5 right-2 bg-surface-hover border border-border-light rounded-full w-[22px] h-[22px] text-text-muted cursor-pointer text-base leading-none flex items-center justify-center z-10"
                        aria-label="Dismiss"
                        title="Dismiss"
                    >
                        ×
                    </button>
                )}
                <img
                    src={url}
                    alt={caption ?? 'Generated diagram'}
                    onLoad={() => setLoaded(true)}
                    className={`block w-full h-auto object-contain transition-opacity duration-400 cursor-pointer ${loaded ? 'opacity-100' : 'opacity-0'}`}
                    draggable={false}
                />
                {caption && <p className="my-1.5 mx-3 mb-2.5 text-text-secondary text-[11px] font-body leading-[1.4] text-center">{caption}</p>}
                {!loaded && <div className="absolute inset-0 bg-surface-alt animate-pulse" />}
            </div>

            {/* Fullscreen Expand Modal */}
            {isExpanded && (
                <div
                    className="fixed inset-0 bg-overlay backdrop-blur-md z-[1210] flex flex-col items-center justify-center p-6 animate-[fadeIn_0.2s_ease] cursor-zoom-out"
                    onClick={() => setIsExpanded(false)}
                    role="dialog"
                    aria-modal="true"
                    aria-label="Expanded diagram"
                >
                    <button
                        onClick={() => setIsExpanded(false)}
                        className="absolute top-6 right-6 bg-surface border-none rounded-full w-10 h-10 text-text-primary cursor-pointer text-xl flex items-center justify-center shadow-md transition-transform duration-200 hover:scale-[1.05]"
                        aria-label="Close fullscreen"
                    >
                        ✕
                    </button>
                    <img
                        src={url}
                        alt={caption ?? 'Expanded diagram'}
                        className="max-w-[90vw] max-h-[80vh] object-contain rounded-md shadow-lg cursor-default"
                        onClick={(e) => e.stopPropagation()} // Prevent close when clicking image
                        draggable={false}
                    />
                    {caption && (
                        <div className="mt-4 bg-surface py-2 px-4 rounded-full shadow-md max-w-[80vw]" onClick={(e) => e.stopPropagation()}>
                            <p className="m-0 text-text-primary text-sm font-body text-center">{caption}</p>
                        </div>
                    )}
                </div>
            )}
        </>
    );
}
